-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기(https://school.programmers.co.kr/learn/courses/30/lessons/151139)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS -- MONTH, CAR_ID, RECORDS 조회
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY -- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서
WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01' AND CAR_ID IN( -- START_DATE가 2022-08-01이상 2022-11-01 미만이고, 서브쿼리에 해당하는 CAR_ID일 경우만
    SELECT CAR_ID -- CAR_ID조회
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY -- CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01' -- START_DATE가 2022-08-01이상, 2022-11-01 미만인 것들만
    GROUP BY CAR_ID -- CAR_ID가 같은것들끼리 그룹으로
    HAVING COUNT(CAR_ID) >= 5 -- 해당 CAR_ID의 개수가 5 이상인 것들만
)
GROUP BY CAR_ID, MONTH(START_DATE) -- CAR_ID, MONTH(START_DATE)가 같은것들끼리 그룹으로
ORDER BY MONTH, CAR_ID DESC -- MONTH 기준으로 오름차순 정렬, 같으면 CAR_ID 기준으로 내림차순 정렬