-- 가격대 별 상품 개수 구하기(https://school.programmers.co.kr/learn/courses/30/lessons/131530)

SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS -- PRICE의 뒷 4글자 버려서 컬럼명 PRICE_GROUP으로, 개수를 PRODUCTS로
-- SELECT FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT -- PRODUCT 테이블에서
GROUP BY PRICE_GROUP -- PRICE_GROUP이 같은 것들끼리 그룹으로
ORDER BY PRICE_GROUP -- PRICE_GROUP을 기준으로 오름차순 정렬