-- 조건에 맞는 사용자와 총 거래금액 조회하기(https://school.programmers.co.kr/learn/courses/30/lessons/164668)

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES -- USER_ID, NICKNAME, TOTAL_SALES 조회
FROM USED_GOODS_BOARD AS B -- USER_GOODS_BOARD 테이블에
JOIN USED_GOODS_USER AS U -- USER_GOODS_USER 테이블 JOIN
ON B.WRITER_ID = U.USER_ID -- B.WRITER_ID와 U.USER_ID가 같은 조건만
WHERE STATUS = 'DONE' -- STATUS가 DONE인 것들만
GROUP BY USER_ID -- USER_ID가 같은것들끼리 그룹으로
HAVING TOTAL_SALES >= 700000 -- TOTAL_SALES가 700000 이상인 것들만
ORDER BY TOTAL_SALES -- TOTAL_SALES기준으로 오름차순 정렬