-- 보호소에서 중성화한 동물

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME -- O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME 조회
FROM ANIMAL_OUTS O -- ANIMAL_OUTS 테이블에
LEFT JOIN ANIMAL_INS I -- ANIMAL_INS 테이블 LEFT JOIN
ON O.ANIMAL_ID = I.ANIMAL_ID -- ANIMAL_ID가 같은 조건만
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' AND -- INTAKE에 Intact가 포함되어 있으면서
      (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%') -- OUTCOME에는 Spayed나 Neutered가 포함되어 있는 것들만
ORDER BY O.ANIMAL_ID -- ANIMAL_ID 기준으로 오름차순 정렬